---
title: "Make data frame for stacked plot"
author: "Alexa Varah"
date: "2023-06-07"
output: html_document
---

# 1. Set up

## 1.1. Load packages and functions
```{r}
rm(list=ls())
library(tidyverse)
library(patchwork) # for panel plots
library("tibble")
library(pBrackets)

nobs <- function(x) length(x[!is.na(x)])
```

## 1.2. Load & tidy data
```{r}
econ_allimp <- read.csv("../output/economic_data_for_analysis-all_imputations.csv", header = T) %>% 
  dplyr::mutate(
    scenario = factor(scenario, levels = c("BAU", "MIT", "CWW")),
    region = factor(region, levels = c("north", "central", "east")),
    soiltype = factor(soiltype, levels = c("heavy", "medium","light")),
    initdenres = factor(initdenres, 
                        levels = c(
                          "LD-LR", "MD-LR",
                          "LD-HR", "MD-HR",
                          "HD-HR", "VD-HR" 
                        )))

# Load low density model runs
# BAU
bau_low <- read.csv("../output/bau_ECOMOD_output_L.csv", header=TRUE) %>% 
  dplyr::select(-Field_no) %>% # remove unnecessary column
  rename_with(stringr::str_replace, # add '.' b4 the number in 'crop' colnames
              pattern = "crop", replacement = "crop.", 
              matches("crop")) %>% 
  rename(meanrotgrossprof = totalrotgrossprof) %>% 
  data.frame()

# MIT
mit_low <- read.csv("../output/mit_ECOMOD_output_L_combined.csv", header=TRUE) %>% 
  dplyr::select(-X) %>% # remove extra column added by R when reading in the file
  rename_with(stringr::str_replace, # add '.' b4 the number in 'crop' colnames
              pattern = "crop", replacement = "crop.", 
              matches("crop")) %>% 
  rename(meanrotgrossprof = totalrotgrossprof) %>% 
  data.frame()

# CWW
cww_low <- read.csv("../output/cww_ECOMOD_output_L.csv", header=TRUE) %>% 
  dplyr::select(-Field_no) %>% # remove unnecessary column
  rename_with(stringr::str_replace, # add '.' b4 the number in 'crop' colnames
              pattern = "crop", replacement = "crop.", 
              matches("crop")) %>% 
  rename(meanrotgrossprof = totalrotgrossprof) %>% 
  data.frame()



# BAU
bau_low_reshaped <- reshape(bau_low, varying=c(2:85), direction="long", 
                            idvar = "field_name", sep = ".", timevar = "rotation") %>% 
  arrange(field_name)

bau_low_tidy <- bau_low_reshaped %>% 
  dplyr::mutate(
    year = rotation,
    initdenres = sub('.*\\_', '', field_name), # extract chrs after last '_'
    
    # extract characters between 1st and 2nd underscore ( x[2] pulls out the 
    # 2nd split string when split on underscores):
    soiltype = sapply(strsplit(field_name, "_"), function(x) x[2]), 
    soiltype = substr(soiltype, start = 1, stop = 1), # extract 1st character
    
    region = sub('_.*', '', field_name), # extract chrs before first '_'
    region = tolower(region),
    
    initcondit = paste(region, soiltype, initdenres, sep = "_"),
    scenario = "BAU",
    ID = paste(scenario, initcondit, rotation, sep = "_")
  ) %>% 
  dplyr::select(-c(meanrotgrossprof, field_name, rotation))

# MIT
mit_low_reshaped <- reshape(mit_low, varying=c(2:85), direction="long", 
                            idvar = "field_name", sep = ".", timevar = "rotation") %>% 
  arrange(field_name)

mit_low_tidy <- mit_low_reshaped %>% 
  dplyr::mutate(
    year = rotation,
    field_name = gsub('\\.', '_', field_name), # replace . with _
    initdenres = sub('_.*', '', field_name), # extract chrs before first '_'
    soiltype = sub('.*\\_', '', field_name), # extract chrs after last '_'
    region = substr(field_name, start = 7, stop = 7), # extract 7th character
    region = tolower(region),
    initcondit = paste(region, soiltype, initdenres, sep = "_"),
    scenario = "MIT",
    ID = paste(scenario, initcondit, rotation, sep = "_")
  ) %>% 
  dplyr::select(-c(meanrotgrossprof, field_name, rotation))

# CWW
cww_low_reshaped <- reshape(cww_low, varying=c(2:85), direction="long", 
                            idvar = "field_name", sep = ".", timevar = "rotation") %>% 
  arrange(field_name)

cww_low_tidy <- cww_low_reshaped %>% 
  dplyr::mutate(
    year = rotation,
    initdenres = sub('.*\\_', '', field_name), # extract chrs after last '_'
    
    # extract characters between 1st and 2nd underscore ( x[2] pulls out the 
    # 2nd split string when split on underscores):
    soiltype = sapply(strsplit(field_name, "_"), function(x) x[2]), 
    soiltype = substr(soiltype, start = 1, stop = 1), # extract 1st character
    
    region = sub('_.*', '', field_name), # extract chrs before first '_'
    region = tolower(region),
    
    initcondit = paste(region, soiltype, initdenres, sep = "_"),
    scenario = "CWW",
    ID = paste(scenario, initcondit, rotation, sep = "_")
  ) %>% 
  dplyr::select(-c(meanrotgrossprof, field_name, rotation))


# join all three
low_run <- rbind(bau_low_tidy, mit_low_tidy, cww_low_tidy)
str(low_run)

# tidy column names and variables
low_run_tidy <- low_run %>% 
  dplyr::mutate(
    scenario = factor(scenario, levels=c("BAU", "MIT", "CWW")),
    # re-name levels of region and soiltype, then re-order levels
    region = forcats::fct_recode(region,
                                 "north" = "n", # new, old
                                 "central" = "c",
                                 "east" = "e"),
    region = factor(region, levels=c("north", "central", "east")),
    soiltype = forcats::fct_recode(soiltype,
                                   "heavy" = "h", # new, old
                                   "medium" = "m",
                                   "light" = "l"),
    soiltype = factor(soiltype, levels=c("heavy", "medium", "light")),
    # specify order of levels for den-res variables
    initdenres = factor(initdenres, 
                        levels = c("VD-HR", "HD-HR", "MD-HR", 
                                   "MD-LR", "LD-HR", "LD-LR")),
    # specify order of levels so later plots are in correct order:
    initcondit = factor(initcondit, levels = c(
      "n_h_VD-HR", "n_m_VD-HR", "n_l_VD-HR", 
      "c_h_VD-HR", "c_m_VD-HR", "c_l_VD-HR",
      "e_h_VD-HR", "e_m_VD-HR", "e_l_VD-HR",
      
      "n_h_HD-HR", "n_m_HD-HR", "n_l_HD-HR",
      "c_h_HD-HR", "c_m_HD-HR", "c_l_HD-HR",
      "e_h_HD-HR", "e_m_HD-HR", "e_l_HD-HR",
      
      "n_h_MD-HR", "n_m_MD-HR", "n_l_MD-HR",
      "c_h_MD-HR", "c_m_MD-HR", "c_l_MD-HR",
      "e_h_MD-HR", "e_m_MD-HR", "e_l_MD-HR",
      
      "n_h_MD-LR", "n_m_MD-LR", "n_l_MD-LR",
      "c_h_MD-LR", "c_m_MD-LR", "c_l_MD-LR",
      "e_h_MD-LR", "e_m_MD-LR", "e_l_MD-LR",
      
      "n_h_LD-HR", "n_m_LD-HR", "n_l_LD-HR",
      "c_h_LD-HR", "c_m_LD-HR", "c_l_LD-HR",
      "e_h_LD-HR", "e_m_LD-HR", "e_l_LD-HR",
      
      "n_h_LD-LR", "n_m_LD-LR", "n_l_LD-LR",
      "c_h_LD-LR", "c_m_LD-LR", "c_l_LD-LR",
      "e_h_LD-LR", "e_m_LD-LR", "e_l_LD-LR"))
  ) %>% 
  dplyr::relocate("ID", "scenario", "region", "soiltype", 
                  "initdenres", "initcondit", "year", "crop", "yield", 
                  "output") %>% 
  dplyr::arrange(scenario, region, soiltype, initdenres)
```

# 2. Calculate cost due to lost yield
Join output column from low_run onto econ_allimp, then do the subtraction.
```{r}
econ_allimp_new <- inner_join(econ_allimp, 
                              low_run_tidy %>% dplyr::select(ID, output),  
                              by = "ID") %>% 
  dplyr::mutate(wtd_cyl = output - wtd_output) # cost due to yield loss
```

# 3. Summarise across 3 den-res levels

```{r}
summarised_df_3DR <- econ_allimp_new %>% 
  # Step 1: create new den-res categories
  dplyr::mutate(
    initdenres_collapsed = fct_recode(initdenres, 
                                      "LD-LR" = "MD-LR",# LD-LR & MD-LR (best case)
                                      "LD-HR" = "MD-HR",# LD-HR & MD-HR (intermediate case) 
                                      "HD-HR" = "VD-HR")# HD-HR & VD-HR (worst case)
  ) %>% 
  
  # Step 2: for weighted variables, calculate means across the new den-res levels and across imputations
  dplyr::group_by(scenario,region,soiltype,initdenres_collapsed,year) %>% 
  dplyr::summarise(across(starts_with("wtd"),.fns = list(
    mean=~mean(.x, na.rm = TRUE), 
    sd=~sd(.x, na.rm = TRUE), 
    se=~sd(.x, na.rm = TRUE)/sqrt(length(.x)),
    n=~nobs(.x),
    ci_l=~mean(.x, na.rm = TRUE) - (1.96 * sd(.x, na.rm = TRUE)/sqrt(length(.x))),
    ci_u=~mean(.x, na.rm = TRUE) + (1.96 * sd(.x, na.rm = TRUE)/sqrt(length(.x)))))) %>% 
  # Step 3: make ID for join
  dplyr::mutate(
    ID = factor(paste(scenario, 
                      substr(region, 1, 1), # just 1st letter of region
                      substr(soiltype, 1, 1), # 1st letter of soiltype
                      initdenres_collapsed, year, sep="_"))
  )

# Add back in other columns 
# pull out columns I need to join back on
econ_distinct_3DR <- econ_allimp_new %>% 
  select(ID, crop, fertcost, seedcost, herbcost, sundry, varcost) %>% 
  distinct(ID, .keep_all=TRUE)

# do the join
econ_3DR <- inner_join(econ_distinct_3DR, summarised_df_3DR,  by = "ID") %>% 
  dplyr::relocate(crop, .after = year) %>%
  dplyr::relocate(fertcost:varcost, .after = crop) %>% 
  dplyr::arrange(scenario, initdenres_collapsed, region, soiltype)

# Clean up
rm(bau_low, mit_low, cww_low,
   bau_low_reshaped, mit_low_reshaped, cww_low_reshaped,
   bau_low_tidy, mit_low_tidy, cww_low_tidy,
   low_run, low_run_tidy, 
   econ_allimp, econ_distinct_3DR, summarised_df_3DR)
```

# 4. Summarise across a rotation
Find the rotation mean values for each scenario and initial den-res.

```{r}
rotn_means <- econ_3DR %>% 
  # create variable for 'other' costs
  dplyr::mutate(other = sundry + fertcost + seedcost) %>% 
  # find rotation mean first
  dplyr::group_by(scenario, region, soiltype, initdenres_collapsed) %>% 
  dplyr::summarize(
    #gross profit
    gp_mean = mean(wtd_gp_mean, na.rm = TRUE),
    gp_ci_l = mean(wtd_gp_mean, na.rm = TRUE) - 
      (1.96 * sd(wtd_gp_mean, na.rm = TRUE) / sqrt(length(wtd_gp_mean))),
    gp_ci_u = mean(wtd_gp_mean, na.rm = TRUE) + 
      (1.96 * sd(wtd_gp_mean, na.rm = TRUE) / sqrt(length(wtd_gp_mean))),
    
    # operations costs
    ops_mean = mean(wtd_opscost_mean, na.rm = TRUE),
    ops_ci_l = mean(wtd_opscost_mean, na.rm = TRUE) - 
      (1.96 * sd(wtd_opscost_mean, na.rm = TRUE) / sqrt(length(wtd_opscost_mean))),
    ops_ci_u = mean(wtd_opscost_mean, na.rm = TRUE) + 
      (1.96 * sd(wtd_opscost_mean, na.rm = TRUE) / sqrt(length(wtd_opscost_mean))),
    
    #herbicide costs (this comprises selective herbs plus glyphosate)
    herb_mean = mean(herbcost, na.rm = TRUE),
    herb_ci_l = mean(herbcost, na.rm = TRUE) - 
      (1.96 * sd(herbcost, na.rm = TRUE) / sqrt(length(herbcost))),
    herb_ci_u = mean(herbcost, na.rm = TRUE) + 
      (1.96 * sd(herbcost, na.rm = TRUE) / sqrt(length(herbcost))),
    
    # costs due to lost yield
    cly_mean = mean(wtd_cyl_mean, na.rm = TRUE),
    cly_ci_l = mean(wtd_cyl_mean, na.rm = TRUE) - 
      (1.96 * sd(wtd_cyl_mean, na.rm = TRUE) / sqrt(length(wtd_cyl_mean))),
    cly_ci_u = mean(wtd_cyl_mean, na.rm = TRUE) + 
      (1.96 * sd(wtd_cyl_mean, na.rm = TRUE) / sqrt(length(wtd_cyl_mean))),
    
    # other costs
    other_mean = mean(other, na.rm = TRUE),
    other_ci_l = mean(other, na.rm = TRUE) - 
      (1.96 * sd(other, na.rm = TRUE) / sqrt(length(other))),
    other_ci_u = mean(other, na.rm = TRUE) + 
      (1.96 * sd(other, na.rm = TRUE) / sqrt(length(other))),
    
    # output
    output_mean = mean(wtd_output_mean, na.rm = TRUE),
    output_ci_l = mean(wtd_output_mean, na.rm = TRUE) - 
      (1.96 * sd(wtd_output_mean, na.rm = TRUE) / sqrt(length(wtd_output_mean))),
    output_ci_u = mean(wtd_output_mean, na.rm = TRUE) + 
      (1.96 * sd(wtd_output_mean, na.rm = TRUE) / sqrt(length(wtd_output_mean)))
  ) %>% 
  
  # then find mean across scenario and initdenres
  dplyr::group_by(scenario, initdenres_collapsed) %>% 
  dplyr::summarize(
    #gross profit
    gp = mean(gp_mean, na.rm = TRUE),
    gp_ci_l = mean(gp_mean, na.rm = TRUE) - 
      (1.96 * sd(gp_mean, na.rm = TRUE) / sqrt(length(gp_mean))),
    gp_ci_u = mean(gp_mean, na.rm = TRUE) + 
      (1.96 * sd(gp_mean, na.rm = TRUE) / sqrt(length(gp_mean))),
    
    # operations costs
    ops = mean(ops_mean, na.rm = TRUE),
    ops_ci_l = mean(ops_mean, na.rm = TRUE) - 
      (1.96 * sd(ops_mean, na.rm = TRUE) / sqrt(length(ops_mean))),
    ops_ci_u = mean(ops_mean, na.rm = TRUE) + 
      (1.96 * sd(ops_mean, na.rm = TRUE) / sqrt(length(ops_mean))), 
    
    #herbicide costs (this comprises selective herbs plus glyphosate)
    herb = mean(herb_mean, na.rm = TRUE),
    herb_ci_l = mean(herb_mean, na.rm = TRUE) - 
      (1.96 * sd(herb_mean, na.rm = TRUE) / sqrt(length(herb_mean))),
    herb_ci_u = mean(herb_mean, na.rm = TRUE) + 
      (1.96 * sd(herb_mean, na.rm = TRUE) / sqrt(length(herb_mean))),
    
    # costs due to lost yield
    cly = mean(cly_mean, na.rm = TRUE),
    cly_ci_l = mean(cly_mean, na.rm = TRUE) - 
      (1.96 * sd(cly_mean, na.rm = TRUE) / sqrt(length(cly_mean))),
    cly_ci_u = mean(cly_mean, na.rm = TRUE) + 
      (1.96 * sd(cly_mean, na.rm = TRUE) / sqrt(length(cly_mean))),
    
    # other costs
    other = mean(other_mean, na.rm = TRUE),
    other_ci_l = mean(other_mean, na.rm = TRUE) - 
      (1.96 * sd(other_mean, na.rm = TRUE) / sqrt(length(other_mean))),
    other_ci_u = mean(other_mean, na.rm = TRUE) + 
      (1.96 * sd(other_mean, na.rm = TRUE) / sqrt(length(other_mean))),
    
    # output
    output = mean(output_mean, na.rm = TRUE),
    output_ci_l = mean(output_mean, na.rm = TRUE) - 
      (1.96 * sd(output_mean, na.rm = TRUE) / sqrt(length(output_mean))),
    output_ci_u = mean(output_mean, na.rm = TRUE) + 
      (1.96 * sd(output_mean, na.rm = TRUE) / sqrt(length(output_mean)))
  ) %>% 
  dplyr::relocate(output:output_ci_u, .after = initdenres_collapsed)

```

# 5. Plot cost components

First get the data into a different format.  

```{r}
df_for_stack <- rotn_means %>% 
  ungroup() %>% 
  dplyr::filter(!scenario == "CWW") %>% 
  droplevels() %>% 
  dplyr::mutate(xval = paste(scenario, initdenres_collapsed, sep="_")) %>% 
  dplyr::select(-c('scenario','initdenres_collapsed')) %>% 
  dplyr::select(xval, herb, ops, cly, other) %>% 
  pivot_longer(!xval, names_to = "cost", values_to = "amount") %>% 
  dplyr::mutate(cost = factor(cost, levels=c("herb", "cly", "ops", "other")))
```


Save data.
```{r}
write.csv(df_for_stack,"../output/data for stacked bar plot.csv", row.names = FALSE)
```


